(setq initial-scratch-message
      ";; MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMWKkddodxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMWO:',;;;;,,,:o0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMWd.'okO0OOOkdc,',cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMNc.cO0OOOOOOOOkc'.;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMWx.,x0OOO0OOOO0kx:.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMXc.cOOOOOOOOOOOOl.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMO,.oO0OOOOOOOOkl.,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMWx.,xO0O00OOOkxc.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMNc.:kO0OOOOkdo;.cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMWo.:k0OOOOkdol,.oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMX:.lOOOO0Okxdo;.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMM0,.d0OOOOOOxdo;.cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMk.,x0OOOOOOxdo;.:XMMMMWWWNNXXKKKKXNWMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMx.,x0OOOO0Oxdd:..:odolc:;,,;;;,,;;;:o0WMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMWx.,k0O0OOOOOkkd:. ...  ...,oxxxxxxdc''oXMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMWKo,.ck0OOOOOO0OOOxc....;:cloxOOOOOOOOOx;.lXMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMXd,'cxOOOOOO0OOOOOOkdc..,oddkO0OOOOOOOO00x,.xWMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMK:.;xO00O00OO0OOOOOOkxd:..lddxOOOOOOOOO000k:.oWMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMW0;.ckOOOOO00OOOOOOOOOkxdl..;odxkOOOkkxdol::,..lNMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMM0;.lOOOOOOOO0OOOO0OOOOkxdo, .,::c:;,,',,,;:cll'.xWMMMMMMMMM
;; MMMMMMMMWWNXKK00KO:.ckOOOOOOOOOO0OOOOOOOkddo,  ...';:lodxkOOO00Ol.;XMMMMMMMMM
;; MMMNKkdlc;,'''..'..;x0OOOOOOOOOOOOOOOOOOxddo, .:lodkOOOOOOO0OOOOo.;KMMMMMMMMM
;; MMXl..';:cloodddo'.lOOOOOOOOOOOOOO0OOOOkdddc..;ddddkOOOOOOOOO00x;.oNMMMMMMMMM
;; MMK; ;kOOO00OOO0kc:x0O0OOOOOOOOOOOOOOkxxddo,..lddddkOOOOOOOkxoc'.lXMMMMMMMMMM
;; MMK; :O0OOOOOOOOkxxOOOO0OOOOOOOO0O0Okxdddo;. .cooodxxdolc:,,,,,..dWMMMMMMMMMM
;; MMK; :O0OOOOOOOOOxxOOOOOOOOOOOOOOOOkddddo:. ...''',,,,,;:cldxkOc.cNMMMMMMMMMM
;; MMK; :O0OOOOOOOOOkkOOOOOOOOOOOOOOkxddddo,..'cllllodxxkOOO0OO00k;.oWMMMMMMMMMM
;; MMK; :O0OOOOOOOOOOOOOOOOO0OOOOkkxddddoc,..cddddxkOOO0OO0OOOOOk:.:KMMMMMMMMMMM
;; MMK; :O0OOOOOOO00OOOOOOO0OOOkkxxxddddol;..;:cldkOOOO0OO00OOko,.lKMMMMMMMMMMMM
;; MMK; :O0OOOOOOOOO0000OOOOOOOOOOOOxdddddo,...''',,;::cllooc;',cONMMMMMMMMMMMMM
;; MMK; :O0OOOOOOOOO00OO000OOOOOOOOOOxddddo,.;oooooolc::;;,..:kKWMMMMMMMMMMMMMMM
;; MMK; :kOOOOO0OOOO0OOOOxclxOOOOOOOOOxdddd;.'lddxOOOOOOkkl.'OMMMMMMMMMMMMMMMMMM
;; MMK; ,dkOOOOOOOOOOOkkxo,.'cdkOO00OOkxdddo;..;:lodddddl:..oNMMMMMMMMMMMMMMMMMM
;; MMK; ,odxxkkkOkkkxxddooc,...,;:cloddolllll:'.......''',cONMMMMMMMMMMMMMMMMMMM
;; MMK; ,odddoooollc:;,'''',:okxdlc::;;;;,,,,,,;;:coddxk0XWMMMMMMMMMMMMMMMMMMMMM
;; MMXl..'''''''',,;;cloxOKNWMMMMMMWWNNNXXXXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMNX0OkkkOO00KXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;; MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")

;; (add-to-list 'initial-frame-alist '(fullscreen . fullboth))

(add-hook 'after-init-hook 'my-scratch-run-scheme)
(defun my-scratch-run-scheme ()
  (with-current-buffer "*scratch*"
    (progn
      (flyspell-mode))))
